const albums = [
    {
      id: 1,
      albumclass: "tcd",
      vinylClass: "tcd_vinyl",
      vinylSrc: "tcd_vinyl.jpg",
      cdSrc: "tcd_cd.webp",
      cdClass: "tcd_cd",
      title: "The College Dropout",
      titleClass: "tcd_title",
      description: "His first album",
      descriptionClass: "tcd_desc",
    },

    {
      id: 2,
      albumclass: "lr",
      vinylClass: "lr_vinyl",
      vinylSrc: "lr_vinyl.webp",
      cdSrc: "lr_cd.png",
      cdClass: "lr_cd",
      title: "Late Registration",
      titleClass: "lr_title",
      description: "His first album",
      descriptionClass: "lr_desc",
    },

    {
      id: 3,
      albumclass: "g",
      vinylClass: "g_vinyl",
      vinylSrc: "g_vinyl.webp",
      cdSrc: "g_cd.png",
      cdClass: "g_cd",
      title: "Graduation",
      titleClass: "g_title",
      description: "His first album",
      descriptionClass: "g_desc",
    },

    {
      id: 4,
      albumclass: "808's",
      vinylClass: "808's_vinyl",
      vinylSrc: "080's_vinyl.jpg",
      cdSrc: "808's_cd.png",
      cdClass: "808's_cd",
      title: "808's and Heartbeak",
      titleClass: "808's_title",
      description: "His first album",
      descriptionClass: "808's_desc",
    },

    {
      id: 5,
      albumclass: "mbdtf",
      vinylClass: "mbdtf_vinyl",
      vinylSrc: "mbdtf_vinyl.jpg",
      cdSrc: "mbdtf_cd.png",
      cdClass: "mbdtf_cd",
      title: "My Beautiful Dark Twisted Fantasy",
      titleClass: "mbdtf_title",
      description: "His first album",
      descriptionClass: "mbdtf_desc",
    },

    {
      id: 6,
      albumclass: "wtt",
      vinylClass: "wtt_vinyl",
      vinylSrc: "wtt_vinyl.jpg",
      cdSrc: "wtt_cd.png",
      cdClass: "wtt_cd",
      title: "Watch The Throne",
      titleClass: "wtt_title",
      description: "His first album",
      descriptionClass: "wtt_desc",
    },

    {
      id: 7,
      albumclass: "yeezus",
      vinylClass: "yeezus_vinyl",
      vinylSrc: "yeezus_vinyl.jpg",
      cdSrc: "yeezus_cd.png",
      cdClass: "yeezus_cd",
      title: "Yeezus",
      titleClass: "yeezus_title",
      description: "His first album",
      descriptionClass: "yeezus_desc",
    },

    {
      id: 8,
      albumclass: "tlop",
      vinylClass: "tlop_vinyl",
      vinylSrc: "tlof_vinyl.jpg",
      cdSrc: "tlof_cd.png",
      cdClass: "tlop_cd",
      title: "The Life of Pablo",
      titleClass: "",
      description: "His first album",
      descriptionClass: "tlop_desc",
    },

    {
      id: 9,
      albumclass: "ye",
      vinylClass: "ye_vinyl",
      vinylSrc: "ye_vinyl.jpg",
      cdSrc: "ye_cd.png",
      cdClass: "ye_cd",
      title: "Ye",
      titleClass: "ye_title",
      description: "His first album",
      descriptionClass: "ye_desc",
    },

    {
      id: 10,
      albumclass: "ksg",
      vinylClass: "ksg_vinyl",
      vinylSrc: "ksg_vinyl.jpeg",
      cdSrc: "ksg_cd.png",
      cdClass: "ksg_cd",
      title: "Kids See Ghosts",
      titleClass: "ksg_title",
      description: "His first album",
      descriptionClass: "ksg_desc",
    },

    {
      id: 11,
      albumclass: "jik",
      vinylClass: "jik_vinyl",
      vinylSrc: "jis_vinyl.jpg",
      cdSrc: "jis_cd.png",
      cdClass: "jik_cd",
      title: "Jesus is King",
      titleClass: "jik_title",
      description: "His first album",
      descriptionClass: "jik_desc",
    },

    {
      id: 12,
      albumclass: "donda",
      vinylClass: "donda_vinyl",
      vinylSrc: "donda_vinyl.jpg",
      cdSrc: "donda_cd.png",
      cdClass: "donda_cd",
      title: "DONDA",
      titleClass: "donda_title",
      description: "His first album",
      descriptionClass: "donda_desc",
    },
  ];

  export default albums;